version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /e/volumes/rabbitmq_data:/data