version: "3.1"

services:
  posgres:
    image: postgres:13.1
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=some
      - POSTGRES_DB=riot
    volumes:
      - /e/volumes/postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  adminer:
    image: adminer:4.7.7
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"